[package]
name = "ibex"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "./core", version = "0.1.0" }
macros = { path = "./macros", version = "0.1.0" }
grass = "0.13.1"
symlink = "0.1.0"

# [features]
# macros = ["dep:macros"]
